# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc98d6fe8f630c24797338cfdc6b121785b34974f9fccbae8cb5ce30c2109a5fce9bbbde4009b034bf9f8e96cbc4d52154c20fd5ef1bb6cdfe2daae6db453169

test:
  secret_key_base: 300f15068bcb6905580a05e3b611df802ead365de9bcae7947c3b1e29801a1e54dcf3a30e21bb17995d06305fd2af7e4db6c4143f22ea0e16caa2835f1cf90a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
